### ISSUE TITLE
TypeError: list_products() got an unexpected keyword argument '_maven'

### ISSUE THREAD

**Issue by obriencj** [release-engineering/rcm-nexus#36]
``` $ nexus-list-products 
Traceback (most recent call last):
  File "/usr/bin/nexus-list-products", line 9, in <module>
    load_entry_point('rcm-nexus==2.0.0', 'console_scripts', 'nexus-list-products')()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 57, in augment_usage_errors
    yield
  File "/usr/lib/python2.6/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
TypeError: list_products() got an unexpected keyword argument '_maven'
```

**Comment by obriencj** [comment]
I've been trying to get this into a position where it fully functions -- had made some adjustments to the spec to deal with the name change, and also with some imports that aren't present in py2.6. This one though seems to be an error in the actual logic of the app itself, so I will stop attempting to produce working RPMs of it for a while.

**Comment by jdcasey** [comment]
Was this from an attempt to execute the script after installing? I guess it has to be...

**Comment by obriencj** [comment]
correct. I've since downgraded to the older 1.10 version on that host.

**Comment by jdcasey** [comment]
I'll revert the PR until we can get this tested in a more realistic environment

**Comment by obriencj** [comment]
may I suggest that you create a 2.0.0 branch first so we can continue hacking on it there? or heck, leave it on master and we can create a 1.10 branch based on before the merge.

**Comment by obriencj** [comment]
found the problem I think
```
@click.option("--java", "--mvn", "---maven", help="Display only java products", is_flag=True, default=False)
```

**Comment by dhladky** [comment]
The tripple dash is indeed an error, but it should not cause the  problem reported here. I asked Jan Rokos to do a test session with me so I can finally try the application in the real environment.

**Comment by obriencj** [comment]
The third string argument is treated as the intended "dest" of the option, the keyword argument it's expecting to supply to the decorated function. It's going through the same translations that it would go through if it were being inferred by the option string. See https://click.palletsprojects.com/en/7.x/options/#name-your-options

Specifically these two examples:

> "-f", "--filename", "dest", the name is dest
> "---f", the name is _f

**Comment by lubomir** [comment]
There's also a difference with the ancient version of click on rcm-dev that it doesn't use the first name, but the last one.

**Comment by dhladky** [comment]
That is something I just wanted to say, that there is probably difference in the order of the actual argument processing between versions. In my environment on both Python 2 and 3 the first option is the one that matters.
